services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
          - "@mailer"
          - "%locale%"
          - 50

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
          - "@oc_platform.email.application_mailer"
        tags:
          - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purge\OCPurge
        arguments:
          - "@doctrine.orm.entity_manager"

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
          - "@oc_platform.beta.html_adder"
          - "2018-06-28"
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    admin.Advert:
        class: OC\PlatformBundle\Admin\AdvertAdmin
        arguments: [~, OC\PlatformBundle\Entity\Advert, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Advert }

    admin.Image:
        class: OC\PlatformBundle\Admin\ImageAdmin
        arguments: [~, OC\PlatformBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image }

    admin.Skill:
        class: OC\PlatformBundle\Admin\SkillAdmin
        arguments: [~, OC\PlatformBundle\Entity\Skill, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Skill }

    admin.Category:
        class: OC\PlatformBundle\Admin\CategoryAdmin
        arguments: [~, OC\PlatformBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.Application:
        class: OC\PlatformBundle\Admin\ApplicationAdmin
        arguments: [~, OC\PlatformBundle\Entity\Application, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Application }
