<?php

namespace OC\PlatformBundle\Entity;
use Doctrine\ORM\QueryBuilder;
use OC\PlatformBundle\Repository\AdvertRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
  public function getApplicationsWithAdvert(int $limit){
    $qb = $this->createQueryBuilder('a')
    ->leftjoin('a.advert', 'ad')
    ->addSelect('ad')
    ->setMaxResults($limit);
    return $qb->getQuery()->getResult();
  }
}
