<?php

namespace OC\PlatformBundle\Entity;
use Doctrine\ORM\QueryBuilder;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
